In [ ]:
import torch
import numpy as np

In [3]:
a = torch.FloatTensor(3, 2)
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
b = torch.zeros(3,3,3)
b

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [9]:
n = np.zeros(shape = (3,2))

c = torch.tensor(n)
c

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)